version: "3.8"
services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=c79dc936551d37156f2d84f47a78ff6f
    volumes:
      - ./db:/rails/db
      - sqlite_data:/data

volumes:
  sqlite_data:
